language: node_js
node_js:
- lts/*
addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN

script:
- npm run lint
- npm test -- --coverage --verbose
- echo 'PUBLIC_URL="/fdbk-data-display/#/"' > .env
- npm run build -- --public-url /fdbk-data-display/
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
