name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Run static analysis and unittests
      run: |
        npm run lint
        npm test -- --coverage --verbose
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cypress tests
      run: |
        docker-compose build
        docker-compose up --exit-code-from test
